import { FileText, Briefcase, FolderOpen, Github, Home, Mail, Linkedin } from "lucide-react";

// Define the actions
export const getActions = (router: { push: (path: string) => void }) => [
  {
    id: "contact",
    name: "Contact",
    shortcut: ["g", "t"],
    keywords: "gt contact email message",
    perform: () => router.push("/contact"),
    icon: <Mail className="w-4 h-4" />,
    section: "GENERAL",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    shortcut: ["g", "l"],
    keywords: "gl linkedin professional network",
    perform: () => window.open("https://www.linkedin.com/in/renatoferreiradev/", "_blank"),
    icon: <Linkedin className="w-4 h-4" />,
    section: "GENERAL",
  },
  {
    id: "github",
    name: "GitHub",
    shortcut: ["g", "g"],
    keywords: "gg github code repository",
    perform: () => window.open("https://github.com/RenatoRJF", "_blank"),
    icon: <Github className="w-4 h-4" />,
    section: "GENERAL",
  },
  {
    id: "home",
    name: "Home",
    shortcut: ["g", "h"],
    keywords: "home gh",
    perform: () => router.push("/"),
    icon: <Home className="w-4 h-4" />,
    section: "GO TO",
  },
  {
    id: "about",
    name: "About",
    shortcut: ["g", "a"],
    keywords: "ga about",
    perform: () => router.push("/about"),
    icon: <FileText className="w-4 h-4" />,
    section: "GO TO",
  },
  {
    id: "career",
    name: "Career",
    shortcut: ["g", "c"],
    keywords: "gc career work job",
    perform: () => router.push("/career"),
    icon: <Briefcase className="w-4 h-4" />,
    section: "GO TO",
  },
  {
    id: "education",
    name: "Education",
    shortcut: ["g", "e"],
    keywords: "ge education university master certifications",
    perform: () => router.push("/education"),
    icon: <FileText className="w-4 h-4" />,
    section: "GO TO",
  },
  {
    id: "projects",
    name: "Projects",
    shortcut: ["g", "p"],
    keywords: "gp projects portfolio work",
    perform: () => router.push("/projects"),
    icon: <FolderOpen className="w-4 h-4" />,
    section: "GO TO",
  },
  {
    id: "opensource",
    name: "Open Source",
    shortcut: ["g", "o"],
    keywords: "github open source go",
    perform: () => router.push("/opensource"),
    icon: <Github className="w-4 h-4" />,
    section: "GO TO",
  },
];
