import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import CommandPalette from "@/components/CommandPalette/CommandPalette";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="min-h-screen bg-black grid grid-rows-[80px_1fr]">
          <Header />

          <div className="p-8 max-w-[800px] w-full mx-auto h-full">
            {children}
          </div>
          
          <CommandPalette />
        </div>
      </body>
    </html>
  );
}
