export const careerHistory = [
    {
      title: "React Tech Lead",
      company: "Mercell",
      location: "Utrecht, Netherlands",
      companyUrl: "https://mercell.com",
      period: "May 2024 – Oct 2025 • 1 yr 5 mos",
    },
    {
      title: "Senior Frontend Engineer",
      company: "MKX Network",
      location: "Amsterdam, Netherlands",
      companyUrl: "https://www.mkxnetwork.com",
      period: "Dec 2023 – Jul 2024 • 7 mos",
    },
    {
      title: "Senior Frontend Engineer",
      company: "Success Factory",
      location: "Amsterdam, Netherlands",
      companyUrl: "https://successfactory.com",
      period: "Dec 2021 – Nov 2023 • 1 yr 11 mos",
    },
    {
      title: "Senior Web3 Frontend Engineer",
      company: "Fujitsu",
      location: "Remote",
      companyUrl: "https://fujitsu.com",
      period: "Mar 2023 – Dec 2023 • 9 mos",
    },
    {
      title: "CTO & Full-Stack Engineer",
      company: "Qarwash.com",
      location: "Remote",
      companyUrl: "",
      period: "May 2021 – May 2022 • 1 yr 1 mos",
    },
    {
      title: "Senior Frontend Engineer",
      company: "SOConnect",
      location: "Amsterdam, Netherlands",
      companyUrl: "https://soconnect.com",
      period: "Jan 2021 – Dec 2021 • 1 yr",
    },
    {
      title: "Frontend Engineer",
      company: "VONQ",
      location: "Rotterdam, Netherlands",
      companyUrl: "https://vonq.com",
      period: "Jul 2019 – Dec 2020 • 1 yr 5 mos",
    },
    {
      title: "Senior Frontend Developer",
      company: "Thales Group",
      location: "Oeiras, Portugal",
      companyUrl: "https://thalesgroup.com",
      period: "Apr 2018 – Jul 2019 • 1 yr 3 mos",
    },
    {
      title: "Frontend Engineer",
      company: "SpotQA",
      location: "Remote",
      companyUrl: "https://spotqa.com",
      period: "Jul 2017 – Mar 2018 • 8 mos",
    },
    {
      title: "Tech Lead Frontend Engineer",
      company: "Alocado",
      location: "Remote",
      companyUrl: "",
      period: "Nov 2016 – Jun 2017 • 7 mos",
    },
    {
      title: "Frontend Developer",
      company: "Planedia",
      location: "Remote",
      companyUrl: "https://planedia.com",
      period: "Oct 2015 – Nov 2016 • 1 yr 1 mo",
    },
    {
      title: "Full-stack Developer",
      company: "Legislative Assembly",
      location: "Recife, Brazil",
      companyUrl: "https://al.leg.br",
      period: "Jun 2013 – Sep 2015 • 2 yrs 3 mos",
    },
  ];